name: example-workflow
on: [push]
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      # - run: sudo apt-get install sshpass
      - run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh adrian@31.14.16.189 -p10922 -o "StrictHostKeyChecking no" "sudo ~/bin/update_AniMATE.sh"
